compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network monadTestnet

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network monadTestnet

verify_Celestial:
	npx hardhat verify --network monadTestnet 0x01577aD97bdf307CD82a3DA2B8862D64E919f43C

verify_Gladiator:
	npx hardhat verify --network monadTestnet 0x04D8d49e2FfD5DFc9a4e004431c68845bbC21A47