compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network b3-testnet

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network b3-testnet

verify_Celestial:
	npx hardhat verify --network b3-testnet 0x49E8c60458f7938D63164D2c115E07D58a64De64

verify_Gladiator:
	npx hardhat verify --network b3-testnet 0xe8B3752d45b29dE75e2A164028FD0a5238aFC507