compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network b3-testnet

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network b3-testnet

verify_Celestial:
	npx hardhat verify --network b3-testnet 0x831D06525dE3ed73E2D3F0C7D8BcA17b7e7b2cA6

verify_Gladiator:
	npx hardhat verify --network b3-testnet 0xd270d8f9cDddb378ed8774CfafCdbB5C9c7E45C8