compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network b3-testnet

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network b3-testnet

verify_Celestial:
	npx hardhat verify --network b3-testnet 0x16a9940bF38116861350f00Cff22FdCF17eABa59

verify_Gladiator:
	npx hardhat verify --network b3-testnet 0x632bE79998304372074F291e78Daf55c6e959C03