GET http://localhost:3000/api/celestial/init/descGen
Content-Type: application/json
{
            "name": "jupiter",
            "type": "god",
            "tier": 1,
            "description": "King of the gods, ruler of the heavens.",
            "buffs": {
                "attack": 10,
                "defense": 8,
                "speed": 7
            },
            "spells": {
                "lightning": 12,
                "smite": 10,
                "tempest": 9
            }
        }